#!/usr/bin/bash

# rename the resources directory and edit all reference to resources
# in html files to be compatible with github pages that does not like
# directory names starting with _

mv resources resources.old
mv _resources resources

# See https://www.cyberciti.biz/faq/how-to-use-sed-to-find-and-replace-text-in-files-in-linux-unix-shell/
find . -type f -name "*.html" -exec sed -i 's/_resources/resources/g' {} +
